exclude: ^tests/fixtures/
exclude: ^README.md/fixtures/
exclude: ^.ruff_cache/fixtures/
exclude: ^.pytest_cache/fixtures/
exclude: ^__pycache__/fixtures/
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
        exclude: ^(doc-source/conf|__pkginfo__|setup|tests/.*)\.py$
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-symlinks
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-shebang-scripts-are-executable
      - id: name-tests-test
        args: ['--pytest-test-first']
      - id: pretty-format-json
        args: ['--autofix', '--indent', '4']
      - id: no-commit-to-branch
        args: ['--branch', 'master', '--branch', 'main', '--pattern', '.*-master$', '--pattern', '.*-main$']
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [--quiet, --fail-under=95]
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['--exclude=tests']
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-dunder-all==0.3.0]
        args: ['--config=setup.cfg', '--ignore=E203,E302,E402,E501,W503,E722,C901', '--max-line-length=200']
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ['--config=setup.cfg']
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.0.2
    hooks:
      - id: pylint
        types: [python]
        args: ['--rcfile=setup.cfg', '--disable=C0209,C0411,E0401,F0401,R0801,R0902,R0903,R0914,W0212,W0105,W0107,C0415,W0613,W0621,W1202,W1203', '--max-line-length=200']
  -   repo: https://github.com/psf/black
      rev: 23.10.1
      hooks:
      -   id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        args: [--check]
#  - repo: local
#    hooks:
#      - id: pytest-cov
#        name: pytest-cov
#        stages: [commit]
#        language: system
#        entry: pytest -v --cov-config=setup.cfg --cov=<project_name>
#        types: [python]
#        pass_filenames: false
#        always_run: true