json_response = {
    "data": {
        "min_news_id": "rouonx4m-1",
        "news_list": [
            {
                "hash_id": "rouonx4m-1",
                "news_type": "NEWS",
                "rank": 0,
                "version": 0,
                "type": "NEWS",
                "read_override": False,
                "fixed_rank": False,
                "news_obj": {
                    "old_hash_id": "20yearold-rape-survivor-killed-with-axe-by-accused-his-brother-in-up-1700561009787",
                    "hash_id": "rouonx4m-1",
                    "author_name": "Deepika Bhatt",
                    "content": "A 20-year-old woman was killed with an axe in broad daylight by two brothers, one of whom was accused of raping her three years ago. The brothers, Pawan and Ashok Nishad, had been released on bail a few days before they killed the woman. Pawan was allegedly harassing the woman to drop the rape case filed against him.",
                    "source_url": "https://www.news18.com/amp/india/ups-19-yr-old-woman-hacked-to-death-by-two-brothers-one-of-them-had-raped-her-3-years-ago-8670566.html?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "source_name": "News18",
                    "title": "20-year-old rape survivor killed with axe by accused, his brother in UP",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/21_tue/img_1700559647987_850.jpg?",
                    "shortened_url": "https://shrts.in/VEmZi",
                    "created_at": 1700561009000,
                    "score": 800,
                    "category_names": ["national"],
                    "relevancy_tags": ["crime"],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 12.33,
                    "targeted_city": [],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "The accused are absconding: Police",
                    "bottom_text": "Tap to read more",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://www.news18.com/amp/india/ups-19-yr-old-woman-hacked-to-death-by-two-brothers-one-of-them-had-raped-her-3-years-ago-8670566.html?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "byline_1": [
                        {"type": "TEXT", "text": "swipe left for more at News18 / "},
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {"type": "TEXT", "text": "short by "},
                        {"type": "TEXT", "text": "Deepika Bhatt"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-22T09:56:28.168Z",
                    "trackers": [],
                    "dfp_tags": "score:800,news:default,cat:national,hash:4,noads:True",
                    "dont_show_ad": True,
                    "poll_tenant": "ENGLISH",
                    "image_for_representation": True,
                    "video_opinion_enabled": True,
                    "language": "english",
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 15500,
                    "is_similar_feed_available": False,
                },
            }
        ],
        "reload_required": True,
        "feed_type": "svd",
    },
    "error": False,
}

category_news_json_response = {
    "data": {
        "total_page": 2382,
        "total_cards": 23819,
        "page_num": 1,
        "suggested_news": [
            {
                "rank": 0,
                "news_type": "NEWS",
                "hash_id": "vasuf11x-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "ev-startup-baaz-bikes-raises-$8m-funding-1700549156329",
                    "hash_id": "vasuf11x-1",
                    "author_name": "Megha",
                    "content": "Electric vehicle startup Baaz Bikes has raised $8 million in Series A funding round led by Singapore-based BIG Capital. Rakuten Capital, and the company's existing investors like Kalaari Capital, 9Unicorns, and Sumant Sinha also participated in the round. Baaz Bikes will used the funding towards refining and enhancing existing products, which include e-scooters, batteries, and swapping stations",
                    "source_url": "https://yourstory.com/2023/11/funding-ev-startup-baaz-bikes-raises-8m?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "source_name": "YourStory.com",
                    "title": "EV startup Baaz Bikes raises $8M funding",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/21_tue/img_1700549001552_474.jpg?",
                    "shortened_url": "https://shrts.in/cB8mH",
                    "created_at": 1700549156000,
                    "score": 600,
                    "category_names": ["business", "startup"],
                    "relevancy_tags": [],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 10.5,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "EV startup Baaz Bikes raises $8M funding",
                    "bottom_text": "EV startup Baaz Bikes raises $8M funding",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://yourstory.com/2023/11/funding-ev-startup-baaz-bikes-raises-8m?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at YourStory.com / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at YourStory.com / ",
                        },
                        {"type": "TIME"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-22T06:45:19.054Z",
                    "trackers": [],
                    "dfp_tags": "score:600,news:default,cat:business,cat:startup,hash:5",
                    "dont_show_ad": False,
                    "poll_tenant": "ENGLISH",
                    "image_for_representation": True,
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 1,
                "news_type": "NEWS",
                "hash_id": "jn7btqxn-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "stop-behaving-like-elitist-punks-mittal-to-openai-cofounder-ilya-1700498909075",
                    "hash_id": "jn7btqxn-1",
                    "author_name": "Mansi Agarwal",
                    "content": 'Shaadi.com Founder Anupam Mittal asked OpenAI\'s Co-founder Ilya Sutskever to "stop behaving like elitist punks" after he said he regretted his participation in the board\'s actions. "Hat-tip to Satya Nadella for pulling one of the biggest coups of history...by hiring Sam Altman," Mittal further stated. "Watch Elon Musk and Mark Zuckerberg as they circle a depleted OpenAI," he added.',
                    "source_url": "https://twitter.com/AnupamMittal/status/1726605184879730894?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "source_name": "X (formerly Twitter)",
                    "title": "Stop behaving like elitist punks: Mittal to OpenAI Co-founder Ilya",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700496328952_643.jpg?",
                    "shortened_url": "https://shrts.in/RjG67",
                    "created_at": 1700498909000,
                    "score": 600,
                    "category_names": ["startup", "technology"],
                    "relevancy_tags": ["startup", "technology"],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 10.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "OpenAI board fired Altman as CEO",
                    "bottom_text": "He has now joined Microsoft",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://twitter.com/AnupamMittal/status/1726605184879730894?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "footer_deck_id": "2c3nrl3V_hashtag",
                    "footer_deck_tag_label": "#OpenAIFiresCEOSamAltman",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at X (formerly Twitter) / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {"type": "TEXT", "text": "short by "},
                        {"type": "TEXT", "text": "Mansi Agarwal"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T16:15:34.417Z",
                    "trackers": [],
                    "dfp_tags": "score:600,news:default,cat:startup,cat:technology,hash:4",
                    "dont_show_ad": False,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 2,
                "news_type": "NEWS",
                "hash_id": "k3vixfrd-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "microsoft-offers-jobs-to-all-openai-employees-report-1700493378508",
                    "hash_id": "k3vixfrd-1",
                    "author_name": "Pragya Swastik",
                    "content": 'More than 500 OpenAI employees in a letter to the company\'s board sought its resignation and claimed, "We may choose to resign and join the newly announced Microsoft subsidiary run by Sam Altman and Greg Brockman." They added, "Microsoft has assured us that there are positions for all OpenAI employees at this new subsidiary should we choose to join."',
                    "source_url": "https://www.hindustantimes.com/technology/over-500-openai-employees-threaten-to-quit-removal-of-all-board-members-sam-altman-microsoft-101700489884495-amp.html?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "source_name": "Hindustan Times",
                    "title": "Microsoft offers jobs to all OpenAI employees: Report",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700492571206_988.jpg?",
                    "shortened_url": "https://shrts.in/YF71z",
                    "created_at": 1700493378000,
                    "score": 800,
                    "category_names": ["business", "startup", "technology"],
                    "relevancy_tags": ["startup", "technology", "business"],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 12.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "OpenAI CEO Sam Altman was fired by board",
                    "bottom_text": "He joined Microsoft to lead its new AI team",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://www.hindustantimes.com/technology/over-500-openai-employees-threaten-to-quit-removal-of-all-board-members-sam-altman-microsoft-101700489884495-amp.html?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "footer_deck_id": "2c3nrl3V_hashtag",
                    "footer_deck_tag_label": "#OpenAIFiresCEOSamAltman",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at Hindustan Times / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {"type": "TEXT", "text": "short by "},
                        {"type": "TEXT", "text": "Pragya Swastik"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T15:10:16.298Z",
                    "trackers": [],
                    "dfp_tags": "score:800,news:default,cat:business,cat:startup,cat:technology,hash:3",
                    "dont_show_ad": False,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 3,
                "news_type": "NEWS",
                "hash_id": "zpehbuxd-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "satya-added-value-worth-amazon-tesla-to-microsoft-in-10-yrs-bahl-1700491443769",
                    "hash_id": "zpehbuxd-1",
                    "author_name": "Mansi Agarwal",
                    "content": 'Snapdeal Co-founder Kunal Bahl called Microsoft CEO Satya Nadella "the greatest business person of this generation" amid OpenAI\'s ex-CEO Sam Altman joining the company. "[Satya] has taken Microsoft\'s market cap from $300 billion to $2.8 trillion," Bahl said. "To put it in context, Satya has added an Amazon and a Tesla to Microsoft in 10 years!" he added.',
                    "source_url": "https://twitter.com/1kunalbahl/status/1726553735382581483?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "source_name": "X (formerly Twitter)",
                    "title": "Satya added value worth Amazon, Tesla to Microsoft in 10 yrs: Bahl",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700486764229_71.jpg?",
                    "shortened_url": "https://shrts.in/nkcJw",
                    "created_at": 1700491443000,
                    "score": 600,
                    "category_names": ["startup", "technology"],
                    "relevancy_tags": ["startup", "technology"],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 10.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "Microsoft is one of OpenAI's investors",
                    "bottom_text": "Tap to know more",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://twitter.com/1kunalbahl/status/1726553735382581483?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at X (formerly Twitter) / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {"type": "TEXT", "text": "short by "},
                        {"type": "TEXT", "text": "Mansi Agarwal"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T13:26:54.835Z",
                    "trackers": [],
                    "dfp_tags": "score:600,news:default,cat:startup,cat:technology,hash:2",
                    "dont_show_ad": False,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 4,
                "news_type": "NEWS",
                "hash_id": "giyiriub-1",
                "type": "NEWS",
                "version": 6,
                "news_obj": {
                    "old_hash_id": "over-500-of-700-employees-at-openai-ask-the-board-to-resign-1700490649029",
                    "hash_id": "giyiriub-1",
                    "author_name": "Pragya Swastik",
                    "content": "Over 500 of 700 OpenAI employees asked the company's board to resign after it fired CEO Sam Altman and removed President Greg Brockman from the board, following which Greg quit OpenAI. The OpenAI employees threatened to quit and join Microsoft if OpenAI's current board didn't resign. A letter addressed to OpenAI's board by employees surfaced on social media on Monday.",
                    "source_url": "https://www.reuters.com/technology/openai-staff-threaten-quit-unless-board-resigns-letter-2023-11-20/",
                    "source_name": "Reuters",
                    "title": "Over 500 OpenAI employees threaten to quit, ask the board to resign",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700490148097_331.jpg?",
                    "shortened_url": "https://shrts.in/XgRcd",
                    "created_at": 1700490649000,
                    "score": 1000,
                    "category_names": ["startup", "technology"],
                    "relevancy_tags": ["startup", "technology"],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 15.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "'You are incapable of overseeing OpenAI'",
                    "bottom_text": "OpenAI employees to the company's board",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://twitter.com/karaswisher/status/1726599700961521762?s=20&utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "footer_deck_id": "2c3nrl3V_hashtag",
                    "footer_deck_tag_label": "#OpenAIFiresCEOSamAltman",
                    "byline_1": [
                        {"type": "TEXT", "text": "swipe left for more at Reuters / "},
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {"type": "TEXT", "text": "short by "},
                        {"type": "TEXT", "text": "Pragya Swastik"},
                    ],
                    "version": 6,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T14:23:01.201Z",
                    "trackers": [],
                    "dfp_tags": "score:1000,news:default,cat:startup,cat:technology,hash:0,noads:True",
                    "dont_show_ad": True,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 5,
                "news_type": "NEWS",
                "hash_id": "86yy63cg-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "i-deeply-regret-my-participation-in-boards-actions-openai-cofounder-ilya-1700488535455",
                    "hash_id": "86yy63cg-1",
                    "author_name": "Pragya Swastik",
                    "content": 'OpenAI\'s Co-founder Ilya Sutskever on Monday posted on X, "I deeply regret my participation in the board\'s actions." He added, "I love everything we\'ve built together and I will do everything I can to reunite the company." Earlier, OpenAI\'s board fired CEO Sam Altman saying it "no longer has confidence" in his ability to continue leading OpenAI.',
                    "source_url": "https://x.com/ilyasut/status/1726590052392956028?s=20&utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "source_name": "X (formerly Twitter)",
                    "title": "I deeply regret my participation in board's actions: OpenAI Co-founder Ilya",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700487784381_868.jpg?",
                    "shortened_url": "https://shrts.in/gM975",
                    "created_at": 1700488535000,
                    "score": 1000,
                    "category_names": ["startup", "technology"],
                    "relevancy_tags": ["startup", "technology"],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 15.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "Fired OpenAI CEO Sam Altman to join Microsoft",
                    "bottom_text": "He will lead a new advanced AI research team",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://twitter.com/satyanadella/status/1726509045803336122?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "footer_deck_id": "2c3nrl3V_hashtag",
                    "footer_deck_tag_label": "#OpenAIFiresCEOSamAltman",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at X (formerly Twitter) / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {"type": "TEXT", "text": "short by "},
                        {"type": "TEXT", "text": "Pragya Swastik"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T13:49:30.627Z",
                    "trackers": [],
                    "dfp_tags": "score:1000,news:default,cat:startup,cat:technology,hash:1,noads:True",
                    "dont_show_ad": True,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 6,
                "news_type": "NEWS",
                "hash_id": "ufzfdslf-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "nykaa-shares-continue-to-perform-jumping-14-in-a-week-1700482123004",
                    "hash_id": "ufzfdslf-1",
                    "author_name": "Pratham Nagpal",
                    "content": "Shares of Nykaa surged 5.5% during the intraday trading on Monday, before giving up some of the gains to end the session 2.9% higher at INR 172.65 on the BSE. Shares of Nykaa have gained 23% in two weeks since the release of its financial statements for the quarter ended September 2023. ",
                    "source_url": "https://inc42.com/buzz/nykaa-continues-to-rally-shares-jump-14-in-a-week/?amp=&utm_campaign=fullarticle&utm_medium=referral&utm_content=&utm_source=inshorts",
                    "source_name": "Inc42 Media",
                    "title": "Nykaa Shares Continue To Perform, Jumping 14% In A Week",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700481788685_78.jpg?",
                    "shortened_url": "https://shrts.in/6oYTd",
                    "created_at": 1700482123000,
                    "score": 600,
                    "category_names": ["business", "startup", "technology"],
                    "relevancy_tags": [],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 10.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "Nykaa Shares Surge 11% Intraday On Friday",
                    "bottom_text": "Tap to learn more",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://inc42.com/buzz/nykaa-shares-surge-11-intraday-to-hit-a-11-month-high/?amp=&utm_campaign=fullarticle&utm_medium=referral&utm_content=bottom-url&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at Inc42 Media / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at Inc42 Media / ",
                        },
                        {"type": "TIME"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T12:07:35.525Z",
                    "trackers": [],
                    "dfp_tags": "score:600,news:default,cat:business,cat:startup,cat:technology,hash:8",
                    "dont_show_ad": False,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 7,
                "news_type": "NEWS",
                "hash_id": "5jthcouk-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "satya-nadella-for-the-win-musk-on-sam-altman-joining-microsoft-1700479835925",
                    "hash_id": "5jthcouk-1",
                    "author_name": "Mansi Agarwal",
                    "content": 'World\'s richest man Elon Musk reacted to OpenAI\'s former CEO Sam Altman joining Microsoft and called it "wild times". "Satya [Nadella] for the win," Musk stated. Microsoft CEO Nadella on Monday announced that Altman will become CEO of a new advanced AI research team within Microsoft and OpenAI\'s ex-President Greg Brockman will also be a part of the group.',
                    "source_url": "https://twitter.com/elonmusk/status/1726540022571299281?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "source_name": "X (formerly Twitter)",
                    "title": "Satya Nadella for the win: Musk on Sam Altman joining Microsoft",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700477444092_644.jpg?",
                    "shortened_url": "https://shrts.in/aEjB6",
                    "created_at": 1700479835000,
                    "score": 600,
                    "category_names": ["business", "startup", "technology"],
                    "relevancy_tags": ["business", "technology", "startup"],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 10.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "'Public must know why OpenAI fired Altman'",
                    "bottom_text": "Musk earlier said",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://twitter.com/elonmusk/status/1726540022571299281?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "footer_deck_id": "2c3nrl3V_hashtag",
                    "footer_deck_tag_label": "#OpenAIFiresCEOSamAltman",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at X (formerly Twitter) / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {"type": "TEXT", "text": "short by "},
                        {"type": "TEXT", "text": "Mansi Agarwal"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T10:51:27.216Z",
                    "trackers": [],
                    "dfp_tags": "score:600,news:default,cat:business,cat:startup,cat:technology,hash:7",
                    "dont_show_ad": False,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 8,
                "news_type": "NEWS",
                "hash_id": "qgzdwyci-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "openai-is-nothing-without-its-people-post-employees-as-altman-joins-microsoft-1700479680992",
                    "hash_id": "qgzdwyci-1",
                    "author_name": "Hiral Goyal",
                    "content": 'Several employees of OpenAI took to X to post "OpenAI is nothing without its people," after its fired CEO Sam Altman was hired by Microsoft to lead a new advanced AI research team. Senior executives, including OpenAI\'s CTO Mira Murati and COO Brad Lightcap, also posted the same. ',
                    "source_url": "https://twitter.com/miramurati/status/1726542556203483392?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "source_name": "X (formerly Twitter)",
                    "title": "'OpenAI is nothing without its people,' post employees as Altman joins Microsoft",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700478792335_570.jpg?",
                    "shortened_url": "https://shrts.in/3Le77",
                    "created_at": 1700479680000,
                    "score": 800,
                    "category_names": ["startup", "technology"],
                    "relevancy_tags": ["startup", "technology"],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 12.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "Altman responded to the posts with a heart emoji",
                    "bottom_text": "Tap to know more",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://www.reuters.com/technology/openai-execs-invite-altman-brockman-headquarters-sunday-the-information-2023-11-19/?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "footer_deck_id": "2c3nrl3V_hashtag",
                    "footer_deck_tag_label": "#OpenAIFiresCEOSamAltman",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at X (formerly Twitter) / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {"type": "TEXT", "text": "short by "},
                        {"type": "TEXT", "text": "Hiral Goyal"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T11:15:10.678Z",
                    "trackers": [],
                    "dfp_tags": "score:800,news:default,cat:startup,cat:technology,hash:2,noads:True",
                    "dont_show_ad": True,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 9,
                "news_type": "NEWS",
                "hash_id": "hrtlqi3n-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "pernia-parent-purple-style-labs-gets-$8-mn-in-series-d-round-1700479422697",
                    "hash_id": "hrtlqi3n-1",
                    "author_name": "Pratham Nagpal",
                    "content": "Through this investment, Pernia Pop-Up Shop's parent Purple Style Labs gets a valuation boost to $352 Mn. The funding round was led by Sanket Parekh of the Pidilite Family Office, with participation from Signet (Harish Shah Family Office), Hira Group Family Office, and a clutch of other investors. ",
                    "source_url": "https://inc42.com/buzz/pernia-parent-purple-style-labs-raises-8-mn-from-family-offices-existing-investors/?amp=&utm_campaign=fullarticle&utm_medium=referral&utm_content=&utm_source=inshorts",
                    "source_name": "Inc42 Media",
                    "title": "Pernia Parent Purple Style Labs Gets $8 Mn In Series D Round",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700479105876_766.jpg?",
                    "shortened_url": "https://shrts.in/ZgPwb",
                    "created_at": 1700479422000,
                    "score": 600,
                    "category_names": ["business", "startup", "technology"],
                    "relevancy_tags": [],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 10.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "Purple Style Lab's $14 Mn Funding Round",
                    "bottom_text": "Tap to learn more",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://inc42.com/buzz/luxury-clothing-startup-purple-style-labs-bags-14-mn-funding-for-global-expansion/?amp=&utm_campaign=fullarticle&utm_medium=referral&utm_content=bottom-url&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at Inc42 Media / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at Inc42 Media / ",
                        },
                        {"type": "TIME"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T11:22:36.088Z",
                    "trackers": [],
                    "dfp_tags": "score:600,news:default,cat:business,cat:startup,cat:technology,hash:7",
                    "dont_show_ad": False,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
        ],
        "news_list": [
            {
                "rank": 0,
                "news_type": "NEWS",
                "hash_id": "vasuf11x-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "ev-startup-baaz-bikes-raises-$8m-funding-1700549156329",
                    "hash_id": "vasuf11x-1",
                    "author_name": "Megha",
                    "content": "Electric vehicle startup Baaz Bikes has raised $8 million in Series A funding round led by Singapore-based BIG Capital. Rakuten Capital, and the company's existing investors like Kalaari Capital, 9Unicorns, and Sumant Sinha also participated in the round. Baaz Bikes will used the funding towards refining and enhancing existing products, which include e-scooters, batteries, and swapping stations",
                    "source_url": "https://yourstory.com/2023/11/funding-ev-startup-baaz-bikes-raises-8m?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "source_name": "YourStory.com",
                    "title": "EV startup Baaz Bikes raises $8M funding",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/21_tue/img_1700549001552_474.jpg?",
                    "shortened_url": "https://shrts.in/cB8mH",
                    "created_at": 1700549156000,
                    "score": 600,
                    "category_names": ["business", "startup"],
                    "relevancy_tags": [],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 10.5,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "EV startup Baaz Bikes raises $8M funding",
                    "bottom_text": "EV startup Baaz Bikes raises $8M funding",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://yourstory.com/2023/11/funding-ev-startup-baaz-bikes-raises-8m?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at YourStory.com / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at YourStory.com / ",
                        },
                        {"type": "TIME"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-22T06:45:19.054Z",
                    "trackers": [],
                    "dfp_tags": "score:600,news:default,cat:business,cat:startup,hash:5",
                    "dont_show_ad": False,
                    "poll_tenant": "ENGLISH",
                    "image_for_representation": True,
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 1,
                "news_type": "NEWS",
                "hash_id": "jn7btqxn-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "stop-behaving-like-elitist-punks-mittal-to-openai-cofounder-ilya-1700498909075",
                    "hash_id": "jn7btqxn-1",
                    "author_name": "Mansi Agarwal",
                    "content": 'Shaadi.com Founder Anupam Mittal asked OpenAI\'s Co-founder Ilya Sutskever to "stop behaving like elitist punks" after he said he regretted his participation in the board\'s actions. "Hat-tip to Satya Nadella for pulling one of the biggest coups of history...by hiring Sam Altman," Mittal further stated. "Watch Elon Musk and Mark Zuckerberg as they circle a depleted OpenAI," he added.',
                    "source_url": "https://twitter.com/AnupamMittal/status/1726605184879730894?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "source_name": "X (formerly Twitter)",
                    "title": "Stop behaving like elitist punks: Mittal to OpenAI Co-founder Ilya",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700496328952_643.jpg?",
                    "shortened_url": "https://shrts.in/RjG67",
                    "created_at": 1700498909000,
                    "score": 600,
                    "category_names": ["startup", "technology"],
                    "relevancy_tags": ["startup", "technology"],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 10.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "OpenAI board fired Altman as CEO",
                    "bottom_text": "He has now joined Microsoft",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://twitter.com/AnupamMittal/status/1726605184879730894?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "footer_deck_id": "2c3nrl3V_hashtag",
                    "footer_deck_tag_label": "#OpenAIFiresCEOSamAltman",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at X (formerly Twitter) / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {"type": "TEXT", "text": "short by "},
                        {"type": "TEXT", "text": "Mansi Agarwal"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T16:15:34.417Z",
                    "trackers": [],
                    "dfp_tags": "score:600,news:default,cat:startup,cat:technology,hash:4",
                    "dont_show_ad": False,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 2,
                "news_type": "NEWS",
                "hash_id": "k3vixfrd-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "microsoft-offers-jobs-to-all-openai-employees-report-1700493378508",
                    "hash_id": "k3vixfrd-1",
                    "author_name": "Pragya Swastik",
                    "content": 'More than 500 OpenAI employees in a letter to the company\'s board sought its resignation and claimed, "We may choose to resign and join the newly announced Microsoft subsidiary run by Sam Altman and Greg Brockman." They added, "Microsoft has assured us that there are positions for all OpenAI employees at this new subsidiary should we choose to join."',
                    "source_url": "https://www.hindustantimes.com/technology/over-500-openai-employees-threaten-to-quit-removal-of-all-board-members-sam-altman-microsoft-101700489884495-amp.html?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "source_name": "Hindustan Times",
                    "title": "Microsoft offers jobs to all OpenAI employees: Report",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700492571206_988.jpg?",
                    "shortened_url": "https://shrts.in/YF71z",
                    "created_at": 1700493378000,
                    "score": 800,
                    "category_names": ["business", "startup", "technology"],
                    "relevancy_tags": ["startup", "technology", "business"],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 12.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "OpenAI CEO Sam Altman was fired by board",
                    "bottom_text": "He joined Microsoft to lead its new AI team",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://www.hindustantimes.com/technology/over-500-openai-employees-threaten-to-quit-removal-of-all-board-members-sam-altman-microsoft-101700489884495-amp.html?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "footer_deck_id": "2c3nrl3V_hashtag",
                    "footer_deck_tag_label": "#OpenAIFiresCEOSamAltman",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at Hindustan Times / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {"type": "TEXT", "text": "short by "},
                        {"type": "TEXT", "text": "Pragya Swastik"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T15:10:16.298Z",
                    "trackers": [],
                    "dfp_tags": "score:800,news:default,cat:business,cat:startup,cat:technology,hash:3",
                    "dont_show_ad": False,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 3,
                "news_type": "NEWS",
                "hash_id": "zpehbuxd-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "satya-added-value-worth-amazon-tesla-to-microsoft-in-10-yrs-bahl-1700491443769",
                    "hash_id": "zpehbuxd-1",
                    "author_name": "Mansi Agarwal",
                    "content": 'Snapdeal Co-founder Kunal Bahl called Microsoft CEO Satya Nadella "the greatest business person of this generation" amid OpenAI\'s ex-CEO Sam Altman joining the company. "[Satya] has taken Microsoft\'s market cap from $300 billion to $2.8 trillion," Bahl said. "To put it in context, Satya has added an Amazon and a Tesla to Microsoft in 10 years!" he added.',
                    "source_url": "https://twitter.com/1kunalbahl/status/1726553735382581483?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "source_name": "X (formerly Twitter)",
                    "title": "Satya added value worth Amazon, Tesla to Microsoft in 10 yrs: Bahl",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700486764229_71.jpg?",
                    "shortened_url": "https://shrts.in/nkcJw",
                    "created_at": 1700491443000,
                    "score": 600,
                    "category_names": ["startup", "technology"],
                    "relevancy_tags": ["startup", "technology"],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 10.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "Microsoft is one of OpenAI's investors",
                    "bottom_text": "Tap to know more",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://twitter.com/1kunalbahl/status/1726553735382581483?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at X (formerly Twitter) / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {"type": "TEXT", "text": "short by "},
                        {"type": "TEXT", "text": "Mansi Agarwal"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T13:26:54.835Z",
                    "trackers": [],
                    "dfp_tags": "score:600,news:default,cat:startup,cat:technology,hash:2",
                    "dont_show_ad": False,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 4,
                "news_type": "NEWS",
                "hash_id": "giyiriub-1",
                "type": "NEWS",
                "version": 6,
                "news_obj": {
                    "old_hash_id": "over-500-of-700-employees-at-openai-ask-the-board-to-resign-1700490649029",
                    "hash_id": "giyiriub-1",
                    "author_name": "Pragya Swastik",
                    "content": "Over 500 of 700 OpenAI employees asked the company's board to resign after it fired CEO Sam Altman and removed President Greg Brockman from the board, following which Greg quit OpenAI. The OpenAI employees threatened to quit and join Microsoft if OpenAI's current board didn't resign. A letter addressed to OpenAI's board by employees surfaced on social media on Monday.",
                    "source_url": "https://www.reuters.com/technology/openai-staff-threaten-quit-unless-board-resigns-letter-2023-11-20/",
                    "source_name": "Reuters",
                    "title": "Over 500 OpenAI employees threaten to quit, ask the board to resign",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700490148097_331.jpg?",
                    "shortened_url": "https://shrts.in/XgRcd",
                    "created_at": 1700490649000,
                    "score": 1000,
                    "category_names": ["startup", "technology"],
                    "relevancy_tags": ["startup", "technology"],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 15.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "'You are incapable of overseeing OpenAI'",
                    "bottom_text": "OpenAI employees to the company's board",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://twitter.com/karaswisher/status/1726599700961521762?s=20&utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "footer_deck_id": "2c3nrl3V_hashtag",
                    "footer_deck_tag_label": "#OpenAIFiresCEOSamAltman",
                    "byline_1": [
                        {"type": "TEXT", "text": "swipe left for more at Reuters / "},
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {"type": "TEXT", "text": "short by "},
                        {"type": "TEXT", "text": "Pragya Swastik"},
                    ],
                    "version": 6,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T14:23:01.201Z",
                    "trackers": [],
                    "dfp_tags": "score:1000,news:default,cat:startup,cat:technology,hash:0,noads:True",
                    "dont_show_ad": True,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 5,
                "news_type": "NEWS",
                "hash_id": "86yy63cg-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "i-deeply-regret-my-participation-in-boards-actions-openai-cofounder-ilya-1700488535455",
                    "hash_id": "86yy63cg-1",
                    "author_name": "Pragya Swastik",
                    "content": 'OpenAI\'s Co-founder Ilya Sutskever on Monday posted on X, "I deeply regret my participation in the board\'s actions." He added, "I love everything we\'ve built together and I will do everything I can to reunite the company." Earlier, OpenAI\'s board fired CEO Sam Altman saying it "no longer has confidence" in his ability to continue leading OpenAI.',
                    "source_url": "https://x.com/ilyasut/status/1726590052392956028?s=20&utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "source_name": "X (formerly Twitter)",
                    "title": "I deeply regret my participation in board's actions: OpenAI Co-founder Ilya",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700487784381_868.jpg?",
                    "shortened_url": "https://shrts.in/gM975",
                    "created_at": 1700488535000,
                    "score": 1000,
                    "category_names": ["startup", "technology"],
                    "relevancy_tags": ["startup", "technology"],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 15.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "Fired OpenAI CEO Sam Altman to join Microsoft",
                    "bottom_text": "He will lead a new advanced AI research team",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://twitter.com/satyanadella/status/1726509045803336122?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "footer_deck_id": "2c3nrl3V_hashtag",
                    "footer_deck_tag_label": "#OpenAIFiresCEOSamAltman",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at X (formerly Twitter) / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {"type": "TEXT", "text": "short by "},
                        {"type": "TEXT", "text": "Pragya Swastik"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T13:49:30.627Z",
                    "trackers": [],
                    "dfp_tags": "score:1000,news:default,cat:startup,cat:technology,hash:1,noads:True",
                    "dont_show_ad": True,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 6,
                "news_type": "NEWS",
                "hash_id": "ufzfdslf-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "nykaa-shares-continue-to-perform-jumping-14-in-a-week-1700482123004",
                    "hash_id": "ufzfdslf-1",
                    "author_name": "Pratham Nagpal",
                    "content": "Shares of Nykaa surged 5.5% during the intraday trading on Monday, before giving up some of the gains to end the session 2.9% higher at INR 172.65 on the BSE. Shares of Nykaa have gained 23% in two weeks since the release of its financial statements for the quarter ended September 2023. ",
                    "source_url": "https://inc42.com/buzz/nykaa-continues-to-rally-shares-jump-14-in-a-week/?amp=&utm_campaign=fullarticle&utm_medium=referral&utm_content=&utm_source=inshorts",
                    "source_name": "Inc42 Media",
                    "title": "Nykaa Shares Continue To Perform, Jumping 14% In A Week",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700481788685_78.jpg?",
                    "shortened_url": "https://shrts.in/6oYTd",
                    "created_at": 1700482123000,
                    "score": 600,
                    "category_names": ["business", "startup", "technology"],
                    "relevancy_tags": [],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 10.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "Nykaa Shares Surge 11% Intraday On Friday",
                    "bottom_text": "Tap to learn more",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://inc42.com/buzz/nykaa-shares-surge-11-intraday-to-hit-a-11-month-high/?amp=&utm_campaign=fullarticle&utm_medium=referral&utm_content=bottom-url&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at Inc42 Media / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at Inc42 Media / ",
                        },
                        {"type": "TIME"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T12:07:35.525Z",
                    "trackers": [],
                    "dfp_tags": "score:600,news:default,cat:business,cat:startup,cat:technology,hash:8",
                    "dont_show_ad": False,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 7,
                "news_type": "NEWS",
                "hash_id": "5jthcouk-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "satya-nadella-for-the-win-musk-on-sam-altman-joining-microsoft-1700479835925",
                    "hash_id": "5jthcouk-1",
                    "author_name": "Mansi Agarwal",
                    "content": 'World\'s richest man Elon Musk reacted to OpenAI\'s former CEO Sam Altman joining Microsoft and called it "wild times". "Satya [Nadella] for the win," Musk stated. Microsoft CEO Nadella on Monday announced that Altman will become CEO of a new advanced AI research team within Microsoft and OpenAI\'s ex-President Greg Brockman will also be a part of the group.',
                    "source_url": "https://twitter.com/elonmusk/status/1726540022571299281?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "source_name": "X (formerly Twitter)",
                    "title": "Satya Nadella for the win: Musk on Sam Altman joining Microsoft",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700477444092_644.jpg?",
                    "shortened_url": "https://shrts.in/aEjB6",
                    "created_at": 1700479835000,
                    "score": 600,
                    "category_names": ["business", "startup", "technology"],
                    "relevancy_tags": ["business", "technology", "startup"],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 10.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "'Public must know why OpenAI fired Altman'",
                    "bottom_text": "Musk earlier said",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://twitter.com/elonmusk/status/1726540022571299281?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "footer_deck_id": "2c3nrl3V_hashtag",
                    "footer_deck_tag_label": "#OpenAIFiresCEOSamAltman",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at X (formerly Twitter) / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {"type": "TEXT", "text": "short by "},
                        {"type": "TEXT", "text": "Mansi Agarwal"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T10:51:27.216Z",
                    "trackers": [],
                    "dfp_tags": "score:600,news:default,cat:business,cat:startup,cat:technology,hash:7",
                    "dont_show_ad": False,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 8,
                "news_type": "NEWS",
                "hash_id": "qgzdwyci-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "openai-is-nothing-without-its-people-post-employees-as-altman-joins-microsoft-1700479680992",
                    "hash_id": "qgzdwyci-1",
                    "author_name": "Hiral Goyal",
                    "content": 'Several employees of OpenAI took to X to post "OpenAI is nothing without its people," after its fired CEO Sam Altman was hired by Microsoft to lead a new advanced AI research team. Senior executives, including OpenAI\'s CTO Mira Murati and COO Brad Lightcap, also posted the same. ',
                    "source_url": "https://twitter.com/miramurati/status/1726542556203483392?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "source_name": "X (formerly Twitter)",
                    "title": "'OpenAI is nothing without its people,' post employees as Altman joins Microsoft",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700478792335_570.jpg?",
                    "shortened_url": "https://shrts.in/3Le77",
                    "created_at": 1700479680000,
                    "score": 800,
                    "category_names": ["startup", "technology"],
                    "relevancy_tags": ["startup", "technology"],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 12.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "Altman responded to the posts with a heart emoji",
                    "bottom_text": "Tap to know more",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://www.reuters.com/technology/openai-execs-invite-altman-brockman-headquarters-sunday-the-information-2023-11-19/?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "footer_deck_id": "2c3nrl3V_hashtag",
                    "footer_deck_tag_label": "#OpenAIFiresCEOSamAltman",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at X (formerly Twitter) / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {"type": "TEXT", "text": "short by "},
                        {"type": "TEXT", "text": "Hiral Goyal"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T11:15:10.678Z",
                    "trackers": [],
                    "dfp_tags": "score:800,news:default,cat:startup,cat:technology,hash:2,noads:True",
                    "dont_show_ad": True,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
            {
                "rank": 9,
                "news_type": "NEWS",
                "hash_id": "hrtlqi3n-1",
                "type": "NEWS",
                "version": 0,
                "news_obj": {
                    "old_hash_id": "pernia-parent-purple-style-labs-gets-$8-mn-in-series-d-round-1700479422697",
                    "hash_id": "hrtlqi3n-1",
                    "author_name": "Pratham Nagpal",
                    "content": "Through this investment, Pernia Pop-Up Shop's parent Purple Style Labs gets a valuation boost to $352 Mn. The funding round was led by Sanket Parekh of the Pidilite Family Office, with participation from Signet (Harish Shah Family Office), Hira Group Family Office, and a clutch of other investors. ",
                    "source_url": "https://inc42.com/buzz/pernia-parent-purple-style-labs-raises-8-mn-from-family-offices-existing-investors/?amp=&utm_campaign=fullarticle&utm_medium=referral&utm_content=&utm_source=inshorts",
                    "source_name": "Inc42 Media",
                    "title": "Pernia Parent Purple Style Labs Gets $8 Mn In Series D Round",
                    "important": False,
                    "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/20_mon/img_1700479105876_766.jpg?",
                    "shortened_url": "https://shrts.in/ZgPwb",
                    "created_at": 1700479422000,
                    "score": 600,
                    "category_names": ["business", "startup", "technology"],
                    "relevancy_tags": [],
                    "tenant": "ENGLISH",
                    "fb_object_id": "",
                    "fb_like_count": 0,
                    "country_code": "IN",
                    "impressive_score": 10.71,
                    "targeted_city": [""],
                    "gallery_image_urls": [],
                    "full_gallery_urls": [],
                    "bottom_headline": "Purple Style Lab's $14 Mn Funding Round",
                    "bottom_text": "Tap to learn more",
                    "darker_fonts": True,
                    "bottom_panel_link": "https://inc42.com/buzz/luxury-clothing-startup-purple-style-labs-bags-14-mn-funding-for-global-expansion/?amp=&utm_campaign=fullarticle&utm_medium=referral&utm_content=bottom-url&utm_source=inshorts",
                    "bottom_type": "DEFAULT",
                    "byline_1": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at Inc42 Media / ",
                        },
                        {"type": "TIME"},
                    ],
                    "byline_2": [
                        {
                            "type": "TEXT",
                            "text": "swipe left for more at Inc42 Media / ",
                        },
                        {"type": "TIME"},
                    ],
                    "version": 0,
                    "position_start_time": "1970-01-01T00:00:00Z",
                    "position_expire_time": "2023-11-21T11:22:36.088Z",
                    "trackers": [],
                    "dfp_tags": "score:600,news:default,cat:business,cat:startup,cat:technology,hash:7",
                    "dont_show_ad": False,
                    "poll_tenant": "ENGLISH",
                    "video_opinion_enabled": True,
                    "show_inshorts_brand_name": True,
                    "crypto_coin_preference": None,
                    "is_overlay_supported": False,
                    "news_type": "NEWS",
                    "is_muted": False,
                    "video_audio_type": "USER_SPECIFIED_AUDIO",
                    "auto_play_type": "AUTO_PLAY_USER_SPECIFIED",
                    "show_in_video_feed_only": False,
                    "similar_threshold": 0,
                    "is_similar_feed_available": False,
                },
            },
        ],
    },
    "error": False,
}
